# Generated by Django 3.0.8 on 2020-07-28 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_order_orderupdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='phone',
            new_name='subject',
        ),
    ]
